backend:
  name: github
  repo: cheryllaird/netlify-cms-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: "Home Page"
        file: "site/content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Banner, name: banner, widget: image }
          - { label: Intro, name: intro, widget: markdown }
      - name: about
        label: About
        file: "site/content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Summary, name: summary, widget: string }
          - { label: About, name: about, widget: markdown }
