backend:
  name: github
  repo: cheryllaird/netlify-cms-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: "Home Page"
        file: "site/content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Banner, name: banner, widget: image }
          - { label: "Home Content", name: body, widget: markdown }
      - name: food
        label: Food
        file: "site/content/food.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Banner, name: banner, widget: image }
          - { label: Menu, name: body, widget: markdown }
      - name: drinks
        label: Drinks
        file: "site/content/drinks.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Banner, name: banner, widget: image }
          - { label: Menu, name: body, widget: markdown }
