backend:
  name: github
  repo: cheryllaird/netlify-cms-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
  label: Pages
  files:
    - name: welcome
    label: Welcome
    file: "site/content/welcome.yml"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown }
    - name: about
    label: About
    file: "site/content/about.yml"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Intro, name: intro, widget: markdown }
