backend:
  name: github
  repo: cheryllaird/netlify-cms-gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: business
    label: "Business Information"
    files:
      - label: "Details"
        name: "meta"
        file: "site/business/meta.md"
        fields:
         - { label: "Name", name: name, widget: string }
         - label: "Address"
           name: "address"
           widget: "object"
           fields:
             - { label: "Street Address", name: "street", widget: "string" }
             - { label: "City", name: "city", widget: "string" }
             - { label: "Postal Code", name: "post-code", widget: "string" }
         - label: "Phone Number"
           name: "phone"
           widget: "object"
           fields:
             - { label: "Primary Number", name: "primaryPhone", widget: "number" }
             - { label: "Secondary Number", name: "secondaryPhone", widget: "number" }

  - name: pages
    label: Pages
    files:
      - name: home
        label: "Home Page"
        file: "site/content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Banner, name: banner, widget: image }
          - { label: "Content", name: body, widget: markdown }
      - name: food
        label: Food
        file: "site/content/food.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Image, name: banner, widget: image }
          - { label: "Content", name: body, widget: markdown }
      - name: drinks
        label: Drinks
        file: "site/content/drinks.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Image, name: banner, widget: image }
          - { label: "Content", name: body, widget: markdown }
